// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLcsI-LXSGHsmJskfrGnC6XykVQonA80',
    appId: '1:947806117858:web:6429bf1a8e66f31d1fa3bb',
    messagingSenderId: '947806117858',
    projectId: 'recipe-app-finki-43c69',
    authDomain: 'recipe-app-finki-43c69.firebaseapp.com',
    storageBucket: 'recipe-app-finki-43c69.firebasestorage.app',
    measurementId: 'G-MYH7PL4J7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEfDihZ8fRFcXLLq_L5Jr0gIAn8wX9kAQ',
    appId: '1:947806117858:android:3d823d8e678367e91fa3bb',
    messagingSenderId: '947806117858',
    projectId: 'recipe-app-finki-43c69',
    storageBucket: 'recipe-app-finki-43c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxjgCaC_D7_iSGFv1oCKk81Fd_7NtEW3w',
    appId: '1:947806117858:ios:040ba97b3444812e1fa3bb',
    messagingSenderId: '947806117858',
    projectId: 'recipe-app-finki-43c69',
    storageBucket: 'recipe-app-finki-43c69.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxjgCaC_D7_iSGFv1oCKk81Fd_7NtEW3w',
    appId: '1:947806117858:ios:040ba97b3444812e1fa3bb',
    messagingSenderId: '947806117858',
    projectId: 'recipe-app-finki-43c69',
    storageBucket: 'recipe-app-finki-43c69.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLcsI-LXSGHsmJskfrGnC6XykVQonA80',
    appId: '1:947806117858:web:f6fbb104249aeb781fa3bb',
    messagingSenderId: '947806117858',
    projectId: 'recipe-app-finki-43c69',
    authDomain: 'recipe-app-finki-43c69.firebaseapp.com',
    storageBucket: 'recipe-app-finki-43c69.firebasestorage.app',
    measurementId: 'G-9H54Z2SGGN',
  );
}
